name: Build and deploy dev images for AWS ECS

on:
  push:
    branches:
      - main

jobs:
  pr-description-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch pull request details
      id: pr
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
        PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL" | jq --raw-output .body)
        echo "::set-output name=description::$PR_DESCRIPTION"

    - name: Use pull request description
      run: |
        PR_DESCRIPTION="${{ steps.pr.outputs.description }}"
        echo "Pull Request Description: $PR_DESCRIPTION"
