name: Fetch PR Details

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Fetch PR details
        id: pr-details
        run: |
          PR_DETAILS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r .body)            
          echo "PR Data: ${PR_DETAILS}"
          echo "::set-output name=pr-details::${PR_DETAILS}"

      - name: Set environment variables
        run: |
          PR_NAME=$(echo "${{ steps.pr-details.outputs.pr-details }}" | jq -r '.title')
          PR_VERSION=$(echo "${{ steps.pr-details.outputs.pr-details }}" | jq -r '.body' | grep -oP '(?<=\*\*Version\*\*: ).*')
          PR_FEATURES=$(echo "${{ steps.pr-details.outputs.pr-details }}" | jq -r '.body' | grep -oP '(?<=### Feature:\r\n)[\s\S]*?(?=\r\n\r\n### Update:)')
          PR_UPDATES=$(echo "${{ steps.pr-details.outputs.pr-details }}" | jq -r '.body' | grep -oP '(?<=### Update:\r\n)[\s\S]*?(?=\r\n\r\n### Bug:)')
          PR_BUGS=$(echo "${{ steps.pr-details.outputs.pr-details }}" | jq -r '.body' | grep -oP '(?<=### Bug:\r\n)[\s\S]*?(?=\r\n\r\n### Additional Notes:)')
          PR_NOTES=$(echo "${{ steps.pr-details.outputs.pr-details }}" | jq -r '.body' | grep -oP '(?<=### Additional Notes:\r\n)[\s\S]*?(?=\r\n \r\n## Issue ticket number)')

          echo "PR_NAME=${PR_NAME}" >> $GITHUB_ENV
          echo "PR_VERSION=${PR_VERSION}" >> $GITHUB_ENV
          echo "PR_FEATURES=${PR_FEATURES}" >> $GITHUB_ENV
          echo "PR_UPDATES=${PR_UPDATES}" >> $GITHUB_ENV
          echo "PR_BUGS=${PR_BUGS}" >> $GITHUB_ENV
          echo "PR_NOTES=${PR_NOTES}" >> $GITHUB_ENV

      - name: Use fetched PR details
        run: |
          echo "Outputs: $(echo '${{ toJson(steps.extract-info.outputs) }}' | jq -r tostring)"
          echo "PR_NAME: ${{ env.PR_NAME }}"
          echo "PR_VERSION: ${{ env.PR_VERSION }}"
          echo "PR_FEATURES: ${{ env.PR_FEATURES }}"
          echo "PR_UPDATES: ${{ env.PR_UPDATES }}"
          echo "PR_BUGS: ${{ env.PR_BUGS }}"
          echo "PR_NOTES: ${{ env.PR_NOTES }}"
