name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract PR information
        id: extract_info
        run: |
          title=$(echo "$PR_BODY" | python -c "import sys, re; match = re.search(r'^\*\*Title:\*\* (.*?)(\n|$)', sys.stdin.read(), re.MULTILINE); print(match.group(1) if match else '')")
          version=$(echo "$PR_BODY" | python -c "import sys, re; match = re.search(r'^\*\*Version:\*\* (.*?)(\n|$)', sys.stdin.read(), re.MULTILINE); print(match.group(1) if match else '')")
          changes=$(echo "$PR_BODY" | python -c "import sys, re; matches = re.findall(r'^\*\*Changes:\*\*\s*(.*?)(\n|$)', sys.stdin.read(), re.MULTILINE); print(','.join(matches) if matches else '')")
          additional_notes=$(echo "$PR_BODY" | python -c "import sys, re; match = re.search(r'^\*\*Additional Notes:\*\* (.*?)(\n|$)', sys.stdin.read(), re.MULTILINE); print(match.group(1) if match else '')")
        
          echo "Raw PR Body: $PR_BODY"
          echo "Extracted Title: '$title'"
          echo "Extracted Version: '$version'"
          echo "Extracted Changes: [$changes]"
          echo "Extracted Additional Notes: '$additional_notes'"
          
          echo "::set-output name=title::$title"
          echo "::set-output name=version::$version"
          echo "::set-output name=changes::$changes"
          echo "::set-output name=additional_notes::$additional_notes"
        env:
          PR_BODY: ${{ github.event.pull_request.body }}

      - name: Display formatted information
        run: |
          echo "Title: '${{ steps.extract_info.outputs.title }}'"
          echo "Version: '${{ steps.extract_info.outputs.version }}'"
          echo "Changes: [${{ steps.extract_info.outputs.changes }}]"
          echo "Additional Notes: '${{ steps.extract_info.outputs.additional_notes }}'"
