name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  extract_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Changes
        run: |
          PR_BODY=${PR_BODY//\*/}
          echo "PR_BODY=$PR_BODY"
          
          PR_BODY=${PR_BODY//\\r/}
          echo "PR_BODY=$PR_BODY"
          
          PR_BODY=${PR_BODY//\\n/}
          echo "PR_BODY=$PR_BODY"
          
          CHANGES=$(echo "$PR_BODY" | sed -n -e '/Changes:/,/Additional Notes:/p' | grep '^-' | sed 's/^- //')
          echo "Changes=$CHANGES_STRING"
          
          CHANGES_STRING=$(echo "$CHANGES" | tr '\n' ',' | sed 's/,$//')
          echo "Changes=$CHANGES_STRING"
          
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
       
      
