name: Test PR Action

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Information from PR Description
        id: extract-info
        run: |
          PR_NAME=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=\*\*Name:\*\* ).*')
          PR_VERSION=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=\*\*Version:\*\* ).*')
          PR_FEATURES=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=### Feature:\n)(.*\n)*' | sed '/^$/d')
          PR_BUGS=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=### Bug:\n)(.*\n)*' | sed '/^$/d')
          PR_NOTES=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=### Additional Notes:\n)(.*\n)*' | sed '/^$/d')
          PR_ISSUE_LINK=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=## Issue ticket number and link\n)(.*\n)*' | sed '/^$/d')

          echo "PR_NAME=$PR_NAME"
          echo "PR_VERSION=$PR_VERSION"
          echo "PR_FEATURES=$PR_FEATURES"
          echo "PR_BUGS=$PR_BUGS"
          echo "PR_NOTES=$PR_NOTES"
          echo "PR_ISSUE_LINK=$PR_ISSUE_LINK"

      - name: Display Extracted Information
        run: |
          echo "Extracted Information:"
          echo "Steps:" ${{steps}}
          echo "Extracted Info:" ${{steps.extract-info}}
          echo "Outputs:" ${{steps.extract-info.outputs}}
          echo "Name: ${{ steps.extract-info.outputs.name }}"
          echo "Version: ${{ steps.extract-info.outputs.version }}"
          echo "Feature: ${{ steps.extract-info.outputs.feature }}"
          echo "Update: ${{ steps.extract-info.outputs.update }}"
          echo "Bug: ${{ steps.extract-info.outputs.bug }}"
          echo "Additional Notes: ${{ steps.extract-info.outputs.additional_notes }}"
