name: Build and deploy dev images for AWS ECS

on:
  push:
    branches:
      - main

jobs:
  pr-description-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print event payload
      run: cat $GITHUB_EVENT_PATH

    - name: Fetch pull request details
      id: pr
      run: |
        API_URL="${{ github.repository.pulls_url }}"
        echo "API URL: $API_URL"
        API_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")
        echo "API Response: $API_RESPONSE"
        PR_DESCRIPTION=$(echo "$API_RESPONSE" | jq --raw-output .body)
        echo "::set-output name=description::$PR_DESCRIPTION"

    - name: Use pull request description
      run: |
        PR_DESCRIPTION="${{ steps.pr.outputs.description }}"
        echo "Pull Request Description: $PR_DESCRIPTION"
