name: Fetch PR Details

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract PR Details
        id: extract_details
        run: |
          # Fetch the PR_BODY from the context
          PR_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r .body)            
          echo "PR Body: ${PR_BODY}"
          
          # Extract Name and Version using regular expressions
          NAME=$(echo "$PR_BODY" | grep -oP '(?<=\*\*Name\*\*: ).*')
          VERSION=$(echo "$PR_BODY" | grep -oP '(?<=\*\*Version\*\*: ).*')

          # Extract Features, Updates, Bugs, and Additional Notes using regular expressions
          FEATURES=$(echo "$PR_BODY" | grep -oP '(?<=### Feature:\n)(.*?)(?=\n\n)')
          UPDATES=$(echo "$PR_BODY" | grep -oP '(?<=### Update:\n)(.*?)(?=\n\n)')
          BUGS=$(echo "$PR_BODY" | grep -oP '(?<=### Bug:\n)(.*?)(?=\n\n)')
          ADDITIONAL_NOTES=$(echo "$PR_BODY" | grep -oP '(?<=### Additional Notes:\n)(.*?)(?=\n\n)')

          # Set the outputs for use in subsequent steps
          echo "::set-output name=NAME::$NAME"
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=FEATURES::$FEATURES"
          echo "::set-output name=UPDATES::$UPDATES"
          echo "::set-output name=BUGS::$BUGS"
          echo "::set-output name=ADDITIONAL_NOTES::$ADDITIONAL_NOTES"

      - name: Use Extracted Details
        run: |
          # Access the extracted details using outputs
          echo "Name: ${{ steps.extract_details.outputs.NAME }}"
          echo "Version: ${{ steps.extract_details.outputs.VERSION }}"
          echo "Features: ${{ steps.extract_details.outputs.FEATURES }}"
          echo "Updates: ${{ steps.extract_details.outputs.UPDATES }}"
          echo "Bugs: ${{ steps.extract_details.outputs.BUGS }}"
          echo "Additional Notes: ${{ steps.extract_details.outputs.ADDITIONAL_NOTES }}"
