name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  extract_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Changes
        run: |
          PR_BODY="**Title:** Test Deployment\r\n\r\n**Version:** Test Version\r\n\r\n**Changes:** \r\n- Test change1\r\n- Test change2\r\n\r\n**Additional Notes:** Test Additional Notes"
          echo "PR_BODY=$PR_BODY"
          
          PR_BODY_NO_NEWLINE=$(echo -e "$PR_BODY" | tr -d '\r\n')
          echo "PR_BODY_NO_NEWLINE=$PR_BODY_NO_NEWLINE"

          PR_BODY_NO_ASTRICK=$(echo -e "$PR_BODY" | tr -d '*')
          echo "PR_BODY_NO_ASTRICK=$PR_BODY_NO_ASTRICK"

          CHANGES_STRING=$(echo "$PR_BODY_NO_NEWLINE" | grep -o '\- [^"]*')
          echo "CHANGES_STRING=$CHANGES_STRING"
          
          CHANGES=$(echo "$CHANGES_STRING" | sed ':a;N;$!ba;s/\n/, /g')
          echo "Changes=$CHANGES"
