name: Build and deploy dev images for AWS ECS

env:
  ECS_SERVICE: hyb-dev-service
  DEPLOYMENT_URL: https://dev-ecs.usehybrid.co/
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  AWS_REGION: ap-southeast-1
  ECS_TASK_DEFINITION_NAME: devBackend

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  extract_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest ECS task definition revision
        run: |
          export ECS_VERSION=$(aws ecs describe-task-definition --region ${{ env.AWS_REGION }} --task-definition ${{ env.ECS_TASK_DEFINITION_NAME }} --query 'taskDefinition.revision' --output text)
          echo "ECS_VERSION: $ECS_VERSION"
          echo "ECS_VERSION=$ECS_VERSION" >> $GITHUB_ENV

      - name: Extract Information from PR Description
        run: |
          TITLE=$(echo "$PR_BODY" | grep -oP '\*\*Title:\*\* \K.*' || true)
          VERSION=$(echo "$PR_BODY" | grep -oP '\*\*Version:\*\* \K.*' || true)
          
          PR_BODY=${PR_BODY//\*/}
          PR_BODY=${PR_BODY//\\r/}
          PR_BODY=${PR_BODY//\\n/}
          PR_BODY=${PR_BODY//\`/}
          PR_BODY=${PR_BODY//\,/}
          PR_BODY=${PR_BODY//\"/}

          CHANGES=$(echo "$PR_BODY" | sed -n -e '/Changes:/,/Additional Notes:/p' | grep '^-' | sed 's/^- //' || true)
          CHANGES_STRING=$(echo "$CHANGES" | tr '\n' ',' | sed 's/,$//' || true)
          echo "Changes=$CHANGES_STRING"

          ADDITIONAL_NOTES=$(echo "$PR_BODY" | sed -n -e '/Additional Notes:/,/Issue ticket number and link/p' | grep '^-' | sed 's/^- //' || true)
          ADDITIONAL_NOTES_STRING=$(echo "$ADDITIONAL_NOTES" | tr '\n' ',' | sed 's/,$//' || true)
          echo "Additional Notes=$ADDITIONAL_NOTES_STRING"

          echo "title=$TITLE :rocket:" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "changes=$CHANGES_STRING" >> $GITHUB_ENV
          echo "additional_notes=$ADDITIONAL_NOTES_STRING" >> $GITHUB_ENV
          
        env:
          PR_BODY: ${{ github.event.pull_request.body }}

      - name: Format Changes List
        id: format_changes
        run: |
          changes="${{ env.changes }}"
          echo "Changes: $changes"
          IFS=, read -ra changes_array <<< "$changes"
          formatted_changes=""
          for change in "${changes_array[@]}"; do
            echo "Current change: $change"
            formatted_changes+="• $change"
          done
          echo "FORMATTED_CHANGES: ${formatted_changes}"
          echo "FORMATTED_CHANGES=${formatted_changes}" >> $GITHUB_ENV

          additional_notes="${{ env.additional_notes }}"
          echo "Additional Notes: $additional_notes"
          IFS=, read -ra additional_notes_array <<< "$additional_notes"
          formatted_notes=""
          for note in "${additional_notes_array[@]}"; do
            echo "Current note: $note"
            formatted_notes+="• $note"
          done
          echo "FORMATTED_NOTES: ${formatted_notes}"
          echo "FORMATTED_NOTES=${formatted_notes}" >> $GITHUB_ENV

      - name: Slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          message: |
            New Deployment: ${{ env.title }}
            
            Environment: Deployment of ${{ env.ECS_SERVICE }} to ECS at ${{
            env.DEPLOYMENT_URL }} completed successfully.
            
            Version: 963
            
            Key Features/Changes:
            ${{ env.FORMATTED_CHANGES }}
            
            Additional Notes: 
            ${{ env.FORMATTED_NOTES }}
          channel: '#test-deployments'
      
