name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract PR Info
        id: extract_info
        run: |
          PR_DESCRIPTION=$(curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
                           jq -r '.body')
          
          echo "Pr Desc: $PR_DESCRIPTION"
          TITLE=$(echo "$PR_DESCRIPTION" | grep -oP '(?<=\*\*Title:\*\* ).*' | head -n 1 || true)
          VERSION=$(echo "$PR_DESCRIPTION" | grep -oP '(?<=\*\*Version:\*\* ).*' | head -n 1 || true)
          CHANGES=$(echo "$PR_DESCRIPTION" | grep -oP '(?<=\*\*Changes:\*\* ).*' | grep -oP '(?<=- ).*' | tr '\n' ',' | sed 's/,$//' || true)

          echo "Title=$TITLE"
          echo "Version=$VERSION"
          echo "Changes=$CHANGES"

        shell: bash

      - name: Store PR Info
        run: |
          echo "TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV
