name: Fetch PR Details

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract PR details
        run: |
          PR_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r .body)            
          echo "PR Body: ${PR_BODY}"
          # Extract Name and Version
          NAME=$(echo "$PR_BODY" | grep '**Name**' | cut -d':' -f2 | tr -d '[:space:]')
          VERSION=$(echo "$PR_BODY" | grep '**Version**' | cut -d':' -f2 | tr -d '[:space:]')

          # Extract Features, Updates, Bugs, and Additional Notes
          FEATURES=$(echo "$PR_BODY" | awk -v RS= '/### Feature:/ {print}' | tail -n +2 | sed '/^$/d')
          UPDATES=$(echo "$PR_BODY" | awk -v RS= '/### Update:/ {print}' | tail -n +2 | sed '/^$/d')
          BUGS=$(echo "$PR_BODY" | awk -v RS= '/### Bug:/ {print}' | tail -n +2 | sed '/^$/d')
          ADDITIONAL_NOTES=$(echo "$PR_BODY" | awk -v RS= '/### Additional Notes:/ {print}' | tail -n +2 | sed '/^$/d')

          # Set output variables for later steps
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "FEATURES=$FEATURES" >> $GITHUB_ENV
          echo "UPDATES=$UPDATES" >> $GITHUB_ENV
          echo "BUGS=$BUGS" >> $GITHUB_ENV
          echo "ADDITIONAL_NOTES=$ADDITIONAL_NOTES" >> $GITHUB_ENV

      - name: Display extracted details
        run: |
          echo "Name: $NAME"
          echo "Version: $VERSION"
          echo "Features: $FEATURES"
          echo "Updates: $UPDATES"
          echo "Bugs: $BUGS"
          echo "Additional Notes: $ADDITIONAL_NOTES"
