name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  extract_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Changes
        run: |
          PR_BODY="**Title:** Test Deployment\r\n\r\n**Version:** Test Version\r\n\r\n**Changes:** \r\n- Test change1\r\n- Test change2\r\n\r\n**Additional Notes:** Test Additional Notes"
          
          CLEAN_BODY=$(echo "$PR_BODY" | tr -d '*\r\n')
          echo "CLEAN_BODY=$CLEAN_BODY"
          
          CHANGES_STRING=$(echo "$CLEAN_BODY" | grep -oP '(?<=- ).*')
          echo "CHANGES_STRING=$CHANGES_STRING"
          
          CHANGES=$(echo "$CHANGES_STRING" | paste -sd "," -)
          echo "Changes=$CHANGES"
