name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract PR information
        id: extract_info
        run: |
          title=$(echo "$PR_BODY" | awk -F': ' '/^**Title:/{print $2}')
          version=$(echo "$PR_BODY" | awk -F': ' '/^**Version:/{print $2}')
          changes=$(echo "$PR_BODY" | awk -F': ' '/^**Changes:/{flag=1; next} /^**/{flag=0} flag{print $2}' | sed "s/^ -//")
          additional_notes=$(echo "$PR_BODY" | awk -F': ' '/^**Additional Notes:/{print $2}')
          
          echo "::set-output name=title::$title"
          echo "::set-output name=version::$version"
          echo "::set-output name=changes::$changes"
          echo "::set-output name=additional_notes::$additional_notes"
        env:
          PR_BODY: ${{ github.event.pull_request.body }}


      - name: Display formatted information
        run: |
          echo "Title: '${{ steps.extract_info.outputs.title }}'"
          echo "Version: '${{ steps.extract_info.outputs.version }}'"
          echo "Changes: [${{ steps.extract_info.outputs.changes }}]"
          echo "Additional Notes: '${{ steps.extract_info.outputs.additional_notes }}'"
