name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  extract_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Changes
        run: |
          PR_BODY="**Title:** Test Deployment\r\n\r\n**Version:** Test Version\r\n\r\n**Changes:** \r\n- Test change1\r\n- Test change2\r\n\r\n**Additional Notes:** Test Additional Notes"
          PR_BODY_NO_NEWLINE=$(echo -e "$PR_BODY" | tr -d '\r\n')
          echo "PR_BODY_NO_NEWLINE=$PR_BODY_NO_NEWLINE"

          CHANGES=$(echo "$PR_BODY_NO_NEWLINE" | awk -F '**Changes:** ' '{print $2}' | awk -F '**Additional Notes:**' '{print $1}' | sed 's/^[ \t]*//;s/[ \t]*$//' | sed 's/\s*,\s*/,/g')
          echo "Changes=$CHANGES"
