name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract Information from PR Description
        id: extract-info
        run: |
          echo "PR DESC: $PR_DESCRIPTION"
          TITLE=$(echo "$PR_DESCRIPTION" | grep -oP '\*\*Title:\*\* \K.*' || true)
          VERSION=$(echo "$PR_DESCRIPTION" | grep -oP '\*\*Version:\*\* \K.*' || true)
          # Extract changes as an array
          IFS=$'\n' CHANGES=($(echo "${{ github.event.pull_request.body }}" | awk -v RS='' '/\*\*Changes:\*\* \K(.|\n)*?(\*\*|$)/' | grep -oP '- .*'))
          echo "Changes: ${CHANGES[@]}"
          ADDITIONAL_NOTES=$(echo "$PR_DESCRIPTION" | grep -oP '\*\*Additional Notes:\*\* \K.*' || true)
          echo "title=$TITLE" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "changes=${CHANGES[@]}" >> $GITHUB_ENV
          echo "additional_notes=$ADDITIONAL_NOTES" >> $GITHUB_ENV

        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}

      - name: Display Extracted Information
        run: |
          echo "Outputs: Title=${{ env.title }} Version=${{ env.version }} Changes=${{ env.changes }} Additional Notes=${{ env.additional_notes }}"
