name: Fetch PR Details

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Fetch PR details1
        run: |
          PR_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r .body)            
          echo "PR Body: ${PR_BODY}"
      
      - name: Extract PR Details
        run: |
          # Extracting Name and Version
          name=$(echo "$PR_BODY" | grep '**Name**' | sed 's/\*\*Name\*\*: //')
          version=$(echo "$PR_BODY" | grep '**Version**' | sed 's/\*\*Version\*\*: //')

          # Extracting Features
          features=$(echo "$PR_BODY" | sed -n '/### Feature:/, /### Update:/p' | grep '- ' | sed 's/- //')

          # Extracting Updates
          updates=$(echo "$PR_BODY" | sed -n '/### Update:/, /### Bug:/p' | grep '- ' | sed 's/- //')

          # Extracting Bugs
          bugs=$(echo "$PR_BODY" | sed -n '/### Bug:/, /### Additional Notes:/p' | grep '- ' | sed 's/- //')

          # Extracting Additional Notes
          additional_notes=$(echo "$PR_BODY" | sed -n '/### Additional Notes:/,$p' | grep '- ' | sed 's/- //')

          # Set output variables
          echo "::set-output name=name::${name}"
          echo "::set-output name=version::${version}"
          echo "::set-output name=features::${features}"
          echo "::set-output name=updates::${updates}"
          echo "::set-output name=bugs::${bugs}"
          echo "::set-output name=additional_notes::${additional_notes}"

      - name: Print PR Details
        run: |
          echo "Name: ${{ steps.pr_details.outputs.name }}"
          echo "Version: ${{ steps.pr_details.outputs.version }}"
          echo "Features: ${{ steps.pr_details.outputs.features }}"
          echo "Updates: ${{ steps.pr_details.outputs.updates }}"
          echo "Bugs: ${{ steps.pr_details.outputs.bugs }}"
          echo "Additional Notes: ${{ steps.pr_details.outputs.additional_notes }}"
