name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract Changes
        id: extract_changes
        run: |
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
            jq -r '.body')
          echo "PR: $PR_DESCRIPTION"
          CHANGES=$(echo "$PR_DESCRIPTION" | grep -oP '(?<=Changes:)\s*[\n\r]*(.*?)(?=\r\n\r\n|$)' | sed 's/^\s*\-\s*//')
          echo "Changes: $CHANGES"
