name: Test PR Action

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Information from PR Description
        id: extract-info
        run: |
          echo "PR Information:"
          echo "Github Token:" ${{ secrets.GITHUB_TOKEN }}
          echo "Github Info:" ${{ github }}
          echo "Github API URL:" ${{ github.api_url }}
          echo "Github Repo:" ${{ github.repository }}
          echo "Github Event Number:" ${{ github.event.number }}
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/2 | jq -r .body)
          NAME=$(echo "$PR_DESCRIPTION" | grep -oP 'Name:\s*\K.*' || true)
          VERSION=$(echo "$PR_DESCRIPTION" | grep -oP 'Version:\s*\K.*' || true)
          UPDATE=$(echo "$PR_DESCRIPTION" | grep -oP 'Update:\s*\K.*' || true)
          FEATURE=$(echo "$PR_DESCRIPTION" | grep -oP -m 1 'Feature:\s*\K.*' | sed '/Bug:/q' || true)
          BUG=$(echo "$PR_DESCRIPTION" | grep -oP -m 1 'Bug:\s*\K.*' | sed '/Additional Notes:/q' || true)
          ADDITIONAL_NOTES=$(echo "$PR_DESCRIPTION" | grep -oP -m 1 'Additional Notes:\s*\K.*' || true)
          echo "::set-output name=name::$NAME"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=feature::$FEATURE"
          echo "::set-output name=update::$UPDATE"
          echo "::set-output name=bug::$BUG"
          echo "::set-output name=additional_notes::$ADDITIONAL_NOTES"

      - name: Display Extracted Information
        run: |
          echo "Extracted Information:"
          echo "Steps:" ${{steps}}
          echo "Extracted Info:" ${{steps.extract-info}}
          echo "Outputs:" ${{steps.extract-info.outputs}}
          echo "Name: ${{ steps.extract-info.outputs.name }}"
          echo "Version: ${{ steps.extract-info.outputs.version }}"
          echo "Feature: ${{ steps.extract-info.outputs.feature }}"
          echo "Update: ${{ steps.extract-info.outputs.update }}"
          echo "Bug: ${{ steps.extract-info.outputs.bug }}"
          echo "Additional Notes: ${{ steps.extract-info.outputs.additional_notes }}"
