name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
    - name: Extract Changes
      run: |
        PR_BODY="**Title:** Test Deployment\r\n\r\n**Version:** Test Version\r\n\r\n**Changes:** \r\n- Test change1\r\n- Test change2\r\n\r\n**Additional Notes:** Test Additional Notes"
        
        # Extract the changes from the PR_BODY string
        CHANGES=$(echo "$PR_BODY" | grep -oP '(?<=- ).*(?=\r\n)')

        # Set the CHANGES as an environment variable
        echo "CHANGES=$CHANGES" >> $GITHUB_ENV

    - name: Show Changes
      run: | 
        echo "Changes: ${{ env.CHANGES }}"
