name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
    - name: Extract Changes
      run: |
        CHANGES=$(echo "$PR_BODY" | grep -oP '(?<=- ).*(?=\r\n)')
        echo "CHANGES=$CHANGES" >> $GITHUB_ENV
      env:
          PR_BODY: ${{ github.event.pull_request.body }}

    - name: Show Changes
      run: | 
        echo "Changes: ${{ env.CHANGES }}"
