name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Image and Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Extract Information from PR Description
        id: extract-info
        run: |
          echo "PR DESC: $PR_DESCRIPTION"
          TITLE=$(echo "$PR_DESCRIPTION" | grep -oP '**Title:**\s*\K.*' || true)
          VERSION=$(echo "$PR_DESCRIPTION" | grep -oP '**Version:**\s*\K.*' || true)
          CHANGES=$(echo "$PR_DESCRIPTION" | grep -oP '**Changes:**\s*\K.*' || true)
          ADDITIONAL_NOTES=$(echo "$PR_DESCRIPTION" | grep -oP '**Additional Notes:**\s*\K.*' || true)
          echo "::set-output name=title::$TITLE"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=changes::$CHANGES"
          echo "::set-output name=additional_notes::$ADDITIONAL_NOTES"
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}

      - name: Display Extracted Information
        run: |
          echo "Outputs: $(echo '${{ toJson(steps.extract-info.outputs) }}' | jq -r tostring)"
          echo "Title: ${{ steps.extract-info.outputs.title }}"
          echo "Version: ${{ steps.extract-info.outputs.version }}"
          echo "Changes: ${{ steps.extract-info.outputs.changes }}"
          echo "Additional Notes: ${{ steps.extract-info.outputs.additional_notes }}"
