name: Build and deploy dev images for AWS ECS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  extract_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Changes
        run: |
          TITLE=$(echo "$PR_BODY" | grep -oP '\*\*Title:\*\* \K.*' || true)
          echo "TITLE=$TITLE"
          
          VERSION=$(echo "$PR_BODY" | grep -oP '\*\*Version:\*\* \K.*' || true)
          echo "VERSION=$VERSION"
          
          PR_BODY=${PR_BODY//\*/}
          PR_BODY=${PR_BODY//\\r/}
          PR_BODY=${PR_BODY//\\n/}

          CHANGES=$(echo "$PR_BODY" | sed -n -e '/Changes:/,/Additional Notes:/p' | grep '^-' | sed 's/^- //')
          CHANGES_STRING=$(echo "$CHANGES" | tr '\n' ',' | sed 's/,$//')
          echo "Changes=$CHANGES_STRING"

          ADDITIONAL_NOTES=$(echo "$PR_BODY" | sed -n -e '/Additional Notes:/,/Issue ticket number and link/p' | grep '^-' | sed 's/^- //')
          ADDITIONAL_NOTES_STRING=$(echo "$ADDITIONAL_NOTES" | tr '\n' ',' | sed 's/,$//')
          echo "Additional Notes=$ADDITIONAL_NOTES_STRING"

          
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
       
      
